apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: dbcont
  name: db
spec:
  containers:
  - image: redis
    name: db
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
