apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    component: apiserver
    provider: kubernetes
  name: app-svc
spec:
  ports:
  - port: 8005
    protocol: TCP
    targetPort: 9000
  selector:
    app: db-pod
status:
  loadBalancer: {}
