version:  '3' 
services:
  wp:
    image: wordpress 
    container_name: wp-web
    ports: 
      - "80:80"
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes: 
      - $PWD/html:/var/www/html"
    networks: 
      - test_net
  db:
    container_name: wp-mysqldb
    ports: 
      - "3306:3306"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes: 
      - $PWD/data:/var/lib/mysql"
    networks: 
      - test_net

networks: 
  test_net:

