apiVersion: v1
kind: Service
metadata:
  name: websvc-nodeport-service
  namespace: dev
spec: 
  type: NodePort
  selector:
    app: nginx-pod
  ports: 
   - name: httpd
     port: 80
     targetPort: 80
     nodePort: 30007
