apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: db-pod
  name: redidb
spec:
  containers:
  - image: redis
    name: redidb
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
