apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: static
  name: static
  namespace: dev
spec:
  containers:
  - image: nginx
    name: static
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
